trainer:
  name: DT-SegFormer
  model_config:
    _target_: SegFormer
    verbose: true
  train_dataset_config:
    _target_: CombinedDataset
    dataset_path: null
    type: train
    augment: true
    padding:
      - 0
      - 0
      - 16
      - 16
    verbose: true
  val_dataset_config:
    _target_: CombinedDataset
    dataset_path: null
    type: val
    padding:
      - 0
      - 0
      - 16
      - 16
    verbose: true
  test_dataset_config:
    _target_: KaeggleDataset
    dataset_path: null
    type: test
    padding:
      - 0
      - 0
      - 16
      - 16
    verbose: true
  dataloader_config:
    _target_: torch.utils.data.dataloader.DataLoader
    shuffle: true
    num_workers: 0
  optimizer_config:
    _target_: torch.optim.adam.Adam
    lr: 0.001
    betas:
    - 0.9
    - 0.999
    weight_decay: 0
  scheduler_config:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    options:
      gamma: 0.5
  logging_config:
    checkpoint_path: checkpoints
  pretrained_path: null
  visualize_output: false
  use_cuda: false
  use_mps: false
  device_id: 0
  early_stoppage: false
  loss_threshold: 0.005
  batch_size: 4
  epochs: 31
  checkpoint_interval: 1
  half_precision: false
  clip_gradients: false
  torch_seed: 42
  use_dataset: true
  use_model: true
  wandb: false
  verbose: true
